export const SET_OBJECT_LIST = 'SET_OBJECT_LIST';
export const SET_OBJECT = 'SET_OBJECT';
export const HANDLE_EDIT = 'HANDLE_EDIT';
export const HANDLE_UPDATE = 'HANDLE_UPDATE';
export const HANDLE_DELETE = 'HANDLE_DELETE';
export const AUTHENTICATE = 'AUTHENTICATE';
