default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["db_user"] %>
  password: <%= ENV["db_password"] %>
  host: localhost
  port: 5432


development:
  <<: *default
  database: foundation_dev

test:
  <<: *default
  database: foundation_test

production:
  <<: *default
  database: foundation
